// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVEY-MRjCKH-nB5NRftWi3X3D5pGSaDA4',
    appId: '1:958814142374:web:132dee03f98fb6b2c6d967',
    messagingSenderId: '958814142374',
    projectId: 'modulixapp',
    authDomain: 'modulixapp.firebaseapp.com',
    storageBucket: 'modulixapp.firebasestorage.app',
    measurementId: 'G-BRFRNQ4Z86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA_WtyRxHDfOYz84Ny60WX00MpYeCPdvg',
    appId: '1:958814142374:android:ecd1350faa040399c6d967',
    messagingSenderId: '958814142374',
    projectId: 'modulixapp',
    storageBucket: 'modulixapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBSepwwborZX_R1Fk6yA0JX8fFsq5W_0',
    appId: '1:958814142374:ios:a3e23f011e187a59c6d967',
    messagingSenderId: '958814142374',
    projectId: 'modulixapp',
    storageBucket: 'modulixapp.firebasestorage.app',
    iosClientId: '958814142374-mvnm6t6ohb4to441nru5i19j7p9kd1un.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBSepwwborZX_R1Fk6yA0JX8fFsq5W_0',
    appId: '1:958814142374:ios:a3e23f011e187a59c6d967',
    messagingSenderId: '958814142374',
    projectId: 'modulixapp',
    storageBucket: 'modulixapp.firebasestorage.app',
    iosClientId: '958814142374-mvnm6t6ohb4to441nru5i19j7p9kd1un.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVEY-MRjCKH-nB5NRftWi3X3D5pGSaDA4',
    appId: '1:958814142374:web:4b3b9e60199beb53c6d967',
    messagingSenderId: '958814142374',
    projectId: 'modulixapp',
    authDomain: 'modulixapp.firebaseapp.com',
    storageBucket: 'modulixapp.firebasestorage.app',
    measurementId: 'G-7Z9NTSN9E2',
  );

}